site_name: Google Sheets User Documentation
site_url: https://samrosati.github.io/google-sheets-user-documentation/
repo_url: https://github.com/SamRosati/google-sheets-user-documentation
repo_name: google-sheets-user-documentation
theme:
  name: material
  logo: assets/google_sheets_icon.png
  favicon: assets/google_sheets_icon.png
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: octicons/sun-16
        name: Dark mode
      primary: green
      accent: light green

    # Light Mode
    - scheme: default
      toggle:
        icon: octicons/moon-16
        name: Light mode
      primary: green
      accent: light green

nav:
  - Introduction: index.md
  - Instructions:
      - Task 1 Creating a Basic Automatic Sum: Instruction-Pages/task1.md
      - Task 2 Alternating Row Colors: Instruction-Pages/task2.md
      - Task 3 Freezing the Header Row: Instruction-Pages/task3.md
      - Task 4 Cleaning Data with "Trim Whitespace": Instruction-Pages/task4.md
  - Glossary: Glossary/index.md
  - Troubleshooting: Troubleshooting-Guide/index.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
