site_name: Google Sheets User Documentation
site_url: https://samrosati.github.io/google-sheets-user-documentation/
repo_url: https://github.com/SamRosati/google-sheets-user-documentation
repo_name: google-sheets-user-documentation
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: octicons/sun-16
        name: Dark mode
      primary: indigo
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: octicons/moon-16
        name: Light mode
      primary: blue
      accent: deep orange

nav:
  - Home: index.md
  - Introduction: Introduction/index.md
  - Instructions:
      - Task 1: Instruction-Pages/task1.md
      - Task 2: Instruction-Pages/task2.md
      - Task 3: Instruction-Pages/task3.md
      - Task 4: Instruction-Pages/task4.md
  - Glossary: Glossary/index.md
  - Troubleshooting: Troubleshooting-Guide/index.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
